# Premium Vietnamese TTS Application
# Production-ready Docker Compose with GPU acceleration
# ZipVoice + FastAPI + React frontend

version: '3.8'

services:
  # Premium Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    
    container_name: vietnamese-tts-backend
    hostname: api-server
    
    volumes:
      - ./backend:/app                       # Backend code (read-write for development)
      - ./data:/data                         # Voice profiles and audio data
      - ./models:/models:ro                  # Vietnamese models (read-only)
      - ./ZipVoice:/ZipVoice:ro              # ZipVoice source (read-only)
      - ./DOING:/DOING                       # Processing directory (read-write for monitoring)
      - /tmp:/tmp                            # Temporary processing files
    
    environment:
      # GPU and CUDA configuration
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_MEMORY_FRACTION=0.9
      
      # Python and application paths
      - PYTHONPATH=/ZipVoice:/app
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      
      # FastAPI configuration
      - WORKERS=1
      - MAX_REQUESTS=1000
      - TIMEOUT=300
      
      # Vietnamese TTS optimization
      - DEFAULT_PROFILE=tina
      - MODEL_DIR=/models/zipvoice_vi
      - CHECKPOINT_NAME=iter-525000-avg-2.pt
    
    # GPU access for AI acceleration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 8G
          cpus: '4.0'
    
    ports:
      - "8000:8000"
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    # Dependency and startup order
    depends_on: []
    
  # Premium Frontend Interface
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    
    container_name: vietnamese-tts-frontend
    hostname: web-server
    
    volumes:
      - ./frontend:/app                      # Frontend code (read-write for development)
      - frontend_node_modules:/app/node_modules  # Persistent node_modules for performance
    
    environment:
      # Development server configuration
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_APP_TITLE=Premium Vietnamese TTS
      - VITE_APP_VERSION=1.0.0
      
      # Performance optimization
      - VITE_HMR_PORT=3001
      - CHOKIDAR_USEPOLLING=true
    
    ports:
      - "3000:3000"      # Main frontend port
      - "3001:3001"      # HMR (Hot Module Reload) port
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: unless-stopped
    
    # Dependency management
    depends_on:
      - backend

# Named volumes for persistence and performance
volumes:
  frontend_node_modules:
    driver: local

# Network configuration for service communication
networks:
  default:
    name: vietnamese-tts-network
    driver: bridge
